name: oadmt_2026_demo
channels:
  - conda-forge
dependencies:
  - boto3
  - chemprop >= 2.1.1
  # - codecov
  # - h5py
  # - hyperopt
  # - intake
  # - intake-parquet
  # - joblib
  # - jupyterlab
  # - loguru
  # - matplotlib
  # - numpy
  # - pandas
  # - pip
  # - python >= 3.12,<3.14
  # - pytorch
  # - pytorch-lightning<=2.6.1
  # - pytest
  # - rdkit
  # - rich
  # - scikit-learn
  # - seaborn
  # - statsmodels
  # # - tabpfn
  # - tabulate
  # - zarr >=3.0.0
  - pip:
    - git+https://github.com/OpenADMET/openadmet-models.git@main
